import Link from "next/link";
import { ArrowRight, Check, Minus } from "lucide-react";
import { buildPageMetadata } from "@/lib/seo/metadata";

export const metadata = buildPageMetadata({ title: "Platforms | I Want That!", description: "Compare Vector for WooCommerce and Shopify, including capabilities and pricing.", path: "/platforms", image: "/images/og/pricing-og.png" });
const capabilities = [["Customer-generated offers", true, true], ["Automated counters", true, true], ["Margin floors", true, true], ["Programs and campaigns", true, true], ["Real-time offer analytics", true, true], ["Downloadable store plugin", true, false], ["Merchant-managed API key", true, false], ["Expanded UCP support", true, false]] as const;
function Mark({ included }: { included: boolean }) { return included ? <Check className="mx-auto h-5 w-5 text-emerald-700" aria-label="Included" /> : <Minus className="mx-auto h-5 w-5 text-slate-400" aria-label="Not included" />; }
export default function PlatformsPage() { return <div className="min-h-screen bg-white"><section className="border-b border-surface-border bg-surface-subtle/50 py-16 md:py-24"><div className="container mx-auto px-4"><p className="text-xs font-bold uppercase tracking-widest text-brand">Platforms</p><h1 className="mt-4 max-w-5xl text-4xl font-bold tracking-tight text-black md:text-6xl">One negotiation platform. Built for your commerce stack.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-neutral-muted md:text-xl">Vector supports WooCommerce and Shopify with an experience and plan structure matched to each platform.</p><Link href="/get-started" className="mt-9 inline-flex items-center gap-2 rounded-askrami bg-brand px-8 py-4 font-semibold text-white transition hover:bg-brand-deep">Get Started<ArrowRight className="h-4 w-4" /></Link></div></section><section className="py-14 md:py-20"><div className="container mx-auto grid gap-6 px-4 lg:grid-cols-2"><article className="rounded-askrami border border-brand/30 bg-brand/5 p-8"><p className="text-xs font-bold uppercase tracking-widest text-brand">WooCommerce</p><h2 className="mt-3 text-3xl font-bold text-black">Full Vector + expanded UCP</h2><p className="mt-4 leading-relaxed text-neutral-muted">Sign up directly with Vector, then use the admin console to download the WooCommerce plugin and create your activation API key.</p><p className="mt-6 font-semibold text-black">WooCommerce pricing is selected in Vector during signup.</p></article><article className="rounded-askrami border border-surface-border bg-white p-8"><p className="text-xs font-bold uppercase tracking-widest text-brand">Shopify</p><h2 className="mt-3 text-3xl font-bold text-black">App Store plans</h2><p className="mt-4 leading-relaxed text-neutral-muted">Install through the Shopify App Store. Shopify billing and capabilities follow the Shopify plan structure.</p><p className="mt-6 font-semibold text-black">Plans start free, with Pro from $35/month.</p></article></div></section><section className="border-y border-surface-border bg-surface-subtle/40 py-14 md:py-20"><div className="container mx-auto px-4"><h2 className="text-3xl font-bold tracking-tight text-black md:text-4xl">Compare platform capabilities</h2><div className="mt-8 overflow-x-auto rounded-askrami border border-surface-border bg-white"><table className="w-full min-w-[620px] text-left"><thead className="border-b border-surface-border bg-surface-subtle"><tr><th className="px-6 py-4">Capability</th><th className="px-6 py-4 text-center">WooCommerce</th><th className="px-6 py-4 text-center">Shopify</th></tr></thead><tbody>{capabilities.map(([name, woo, shopify]) => <tr key={name} className="border-b border-surface-border last:border-0"><th className="px-6 py-4 text-sm font-medium text-slate-800">{name}</th><td className="px-6 py-4"><Mark included={woo} /></td><td className="px-6 py-4"><Mark included={shopify} /></td></tr>)}</tbody></table></div></div></section></div>; }

